create table EMPLOYEES
(
    ID NUMBER generated as identity,
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50),
    PHONENUMBER VARCHAR2(50),
    EMAIL VARCHAR2(50),
    JOBTITLE VARCHAR2(50),
    DEPARTMENT VARCHAR2(50),
    EMPLOYEEID VARCHAR2(50),
    STARTDATE DATE
)


