name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: ${{ secrets.IMAGE_NAME }}
          image_tag: latest
          # dockerfile: ./docker/Dockerfile.prod
          # context: ./docker